begin_unit
begin_comment
comment|/**************************************************************************** ** ** Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies). ** All rights reserved. ** Contact: Nokia Corporation (qt-info@nokia.com) ** ** This file is part of the QtOpenGL module of the Qt Toolkit. ** ** $QT_BEGIN_LICENSE:LGPL$ ** No Commercial Usage ** This file contains pre-release code and may not be distributed. ** You may use this file in accordance with the terms and conditions ** contained in the Technology Preview License Agreement accompanying ** this package. ** ** GNU Lesser General Public License Usage ** Alternatively, this file may be used under the terms of the GNU Lesser ** General Public License version 2.1 as published by the Free Software ** Foundation and appearing in the file LICENSE.LGPL included in the ** packaging of this file.  Please review the following information to ** ensure the GNU Lesser General Public License version 2.1 requirements ** will be met: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html. ** ** In addition, as a special exception, Nokia gives you certain additional ** rights.  These rights are described in the Nokia Qt LGPL Exception ** version 1.1, included in the file LGPL_EXCEPTION.txt in this package. ** ** If you have questions regarding the use of this file, please contact ** Nokia at qt-info@nokia.com. ** ** ** ** ** ** ** ** ** $QT_END_LICENSE$ ** ****************************************************************************/
end_comment
begin_include
include|#
directive|include
file|"qplatformglcontext_qpa.h"
end_include
begin_include
include|#
directive|include
file|"qguiglcontext_qpa.h"
end_include
begin_include
include|#
directive|include
file|"qwindow.h"
end_include
begin_include
include|#
directive|include
file|<QtCore/QThreadStorage>
end_include
begin_include
include|#
directive|include
file|<QtCore/QThread>
end_include
begin_include
include|#
directive|include
file|<QtGui/private/qguiapplication_p.h>
end_include
begin_include
include|#
directive|include
file|<QDebug>
end_include
begin_class
DECL|class|QGuiGLThreadContext
class|class
name|QGuiGLThreadContext
block|{
public|public:
DECL|function|~QGuiGLThreadContext
name|~
name|QGuiGLThreadContext
parameter_list|()
block|{
if|if
condition|(
name|context
condition|)
name|context
operator|->
name|doneCurrent
argument_list|()
expr_stmt|;
block|}
DECL|member|context
name|QGuiGLContext
modifier|*
name|context
decl_stmt|;
block|}
class|;
end_class
begin_decl_stmt
DECL|variable|qwindow_context_storage
specifier|static
name|QThreadStorage
argument_list|<
name|QGuiGLThreadContext
modifier|*
argument_list|>
name|qwindow_context_storage
decl_stmt|;
end_decl_stmt
begin_class
DECL|class|QGuiGLContextPrivate
class|class
name|QGuiGLContextPrivate
block|{
public|public:
DECL|function|QGuiGLContextPrivate
name|QGuiGLContextPrivate
parameter_list|()
member_init_list|:
name|qGLContextHandle
argument_list|(
literal|0
argument_list|)
member_init_list|,
name|platformGLContext
argument_list|(
literal|0
argument_list|)
member_init_list|,
name|shareContext
argument_list|(
literal|0
argument_list|)
block|{     }
DECL|function|~QGuiGLContextPrivate
specifier|virtual
name|~
name|QGuiGLContextPrivate
parameter_list|()
block|{
comment|//do not delete the QGLContext handle here as it is deleted in
comment|//QWidgetPrivate::deleteTLSysExtra()
block|}
DECL|member|qGLContextHandle
name|void
modifier|*
name|qGLContextHandle
decl_stmt|;
DECL|member|qGLContextDeleteFunction
name|void
function_decl|(
modifier|*
name|qGLContextDeleteFunction
function_decl|)
parameter_list|(
name|void
modifier|*
name|handle
parameter_list|)
function_decl|;
DECL|member|platformGLContext
name|QPlatformGLContext
modifier|*
name|platformGLContext
decl_stmt|;
DECL|member|shareContext
name|QGuiGLContext
modifier|*
name|shareContext
decl_stmt|;
specifier|static
name|void
name|setCurrentContext
parameter_list|(
name|QGuiGLContext
modifier|*
name|context
parameter_list|)
function_decl|;
block|}
class|;
end_class
begin_function
DECL|function|setCurrentContext
name|void
name|QGuiGLContextPrivate
operator|::
name|setCurrentContext
parameter_list|(
name|QGuiGLContext
modifier|*
name|context
parameter_list|)
block|{
name|QGuiGLThreadContext
modifier|*
name|threadContext
init|=
name|qwindow_context_storage
operator|.
name|localData
argument_list|()
decl_stmt|;
if|if
condition|(
operator|!
name|threadContext
condition|)
block|{
if|if
condition|(
operator|!
name|QThread
operator|::
name|currentThread
argument_list|()
condition|)
block|{
name|qWarning
argument_list|(
literal|"No QTLS available. currentContext wont work"
argument_list|)
expr_stmt|;
return|return;
block|}
name|threadContext
operator|=
operator|new
name|QGuiGLThreadContext
expr_stmt|;
name|qwindow_context_storage
operator|.
name|setLocalData
argument_list|(
name|threadContext
argument_list|)
expr_stmt|;
block|}
name|threadContext
operator|->
name|context
operator|=
name|context
expr_stmt|;
block|}
end_function
begin_comment
comment|/*!   Returns the last context which called makeCurrent. This function is thread aware. */
end_comment
begin_function
DECL|function|currentContext
name|QGuiGLContext
modifier|*
name|QGuiGLContext
operator|::
name|currentContext
parameter_list|()
block|{
name|QGuiGLThreadContext
modifier|*
name|threadContext
init|=
name|qwindow_context_storage
operator|.
name|localData
argument_list|()
decl_stmt|;
if|if
condition|(
name|threadContext
condition|)
block|{
return|return
name|threadContext
operator|->
name|context
return|;
block|}
return|return
literal|0
return|;
block|}
end_function
begin_function
DECL|function|handle
name|QPlatformGLContext
modifier|*
name|QGuiGLContext
operator|::
name|handle
parameter_list|()
specifier|const
block|{
name|Q_D
argument_list|(
specifier|const
name|QGuiGLContext
argument_list|)
expr_stmt|;
return|return
name|d
operator|->
name|platformGLContext
return|;
block|}
end_function
begin_comment
comment|/*!   Creates a new GL context with the given format and shared context. */
end_comment
begin_constructor
DECL|function|QGuiGLContext
name|QGuiGLContext
operator|::
name|QGuiGLContext
parameter_list|(
specifier|const
name|QGuiGLFormat
modifier|&
name|format
parameter_list|,
name|QGuiGLContext
modifier|*
name|shareContext
parameter_list|)
member_init_list|:
name|d_ptr
argument_list|(
operator|new
name|QGuiGLContextPrivate
argument_list|()
argument_list|)
block|{
name|Q_D
argument_list|(
name|QGuiGLContext
argument_list|)
expr_stmt|;
name|QPlatformGLContext
modifier|*
name|share
init|=
name|shareContext
condition|?
name|shareContext
operator|->
name|handle
argument_list|()
else|:
literal|0
decl_stmt|;
name|d
operator|->
name|shareContext
operator|=
name|shareContext
expr_stmt|;
name|d
operator|->
name|platformGLContext
operator|=
name|QGuiApplicationPrivate
operator|::
name|platformIntegration
argument_list|()
operator|->
name|createPlatformGLContext
argument_list|(
name|format
argument_list|,
name|share
argument_list|)
expr_stmt|;
block|}
end_constructor
begin_comment
comment|/*!   If this is the current context for the thread, doneCurrent is called */
end_comment
begin_destructor
DECL|function|~QGuiGLContext
name|QGuiGLContext
operator|::
name|~
name|QGuiGLContext
parameter_list|()
block|{
name|Q_D
argument_list|(
name|QGuiGLContext
argument_list|)
expr_stmt|;
if|if
condition|(
name|QGuiGLContext
operator|::
name|currentContext
argument_list|()
operator|==
name|this
condition|)
name|doneCurrent
argument_list|()
expr_stmt|;
operator|delete
name|d
operator|->
name|platformGLContext
expr_stmt|;
block|}
end_destructor
begin_function
DECL|function|isValid
name|bool
name|QGuiGLContext
operator|::
name|isValid
parameter_list|()
specifier|const
block|{
name|Q_D
argument_list|(
specifier|const
name|QGuiGLContext
argument_list|)
expr_stmt|;
return|return
name|d
operator|->
name|platformGLContext
operator|!=
literal|0
return|;
block|}
end_function
begin_comment
comment|/*!   If surface is 0 this is equivalent to calling doneCurrent(). */
end_comment
begin_function
DECL|function|makeCurrent
name|bool
name|QGuiGLContext
operator|::
name|makeCurrent
parameter_list|(
name|QPlatformGLSurface
modifier|*
name|surface
parameter_list|)
block|{
name|Q_D
argument_list|(
name|QGuiGLContext
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|d
operator|->
name|platformGLContext
condition|)
return|return
literal|false
return|;
if|if
condition|(
operator|!
name|surface
condition|)
block|{
name|doneCurrent
argument_list|()
expr_stmt|;
return|return
literal|true
return|;
block|}
if|if
condition|(
name|d
operator|->
name|platformGLContext
operator|->
name|makeCurrent
argument_list|(
operator|*
name|surface
argument_list|)
condition|)
block|{
name|QGuiGLContextPrivate
operator|::
name|setCurrentContext
argument_list|(
name|this
argument_list|)
expr_stmt|;
return|return
literal|true
return|;
block|}
return|return
literal|false
return|;
block|}
end_function
begin_comment
comment|/*!     Convenience function for calling makeCurrent with a 0 surface. */
end_comment
begin_function
DECL|function|doneCurrent
name|void
name|QGuiGLContext
operator|::
name|doneCurrent
parameter_list|()
block|{
name|Q_D
argument_list|(
name|QGuiGLContext
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|d
operator|->
name|platformGLContext
condition|)
return|return;
name|d
operator|->
name|platformGLContext
operator|->
name|doneCurrent
argument_list|()
expr_stmt|;
name|QGuiGLContextPrivate
operator|::
name|setCurrentContext
argument_list|(
literal|0
argument_list|)
expr_stmt|;
block|}
end_function
begin_function
DECL|function|swapBuffers
name|void
name|QGuiGLContext
operator|::
name|swapBuffers
parameter_list|(
name|QPlatformGLSurface
modifier|*
name|surface
parameter_list|)
block|{
name|Q_D
argument_list|(
name|QGuiGLContext
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|d
operator|->
name|platformGLContext
condition|)
return|return;
if|if
condition|(
operator|!
name|surface
condition|)
block|{
name|qWarning
argument_list|()
operator|<<
literal|"QGuiGLContext::swapBuffers() called with null argument"
expr_stmt|;
return|return;
block|}
name|d
operator|->
name|platformGLContext
operator|->
name|swapBuffers
argument_list|(
operator|*
name|surface
argument_list|)
expr_stmt|;
block|}
end_function
begin_macro
DECL|function|getProcAddress
name|void
argument_list|(
argument|*QGuiGLContext::getProcAddress(const QByteArray&procName)
argument_list|)
end_macro
begin_expr_stmt
DECL|function|getProcAddress
operator|(
operator|)
block|{
name|Q_D
argument_list|(
name|QGuiGLContext
argument_list|)
block|;
if|if
condition|(
operator|!
name|d
operator|->
name|platformGLContext
condition|)
return|return
literal|0
return|;
end_expr_stmt
begin_return
return|return
name|d
operator|->
name|platformGLContext
operator|->
name|getProcAddress
argument_list|(
name|procName
argument_list|)
return|;
end_return
begin_macro
unit|}  QGuiGLFormat
DECL|function|format
name|QGuiGLContext
end_macro
begin_expr_stmt
DECL|function|format
operator|::
name|format
operator|(
operator|)
specifier|const
block|{
name|Q_D
argument_list|(
specifier|const
name|QGuiGLContext
argument_list|)
block|;
if|if
condition|(
operator|!
name|d
operator|->
name|platformGLContext
condition|)
return|return
name|QGuiGLFormat
argument_list|()
return|;
end_expr_stmt
begin_return
return|return
name|d
operator|->
name|platformGLContext
operator|->
name|format
argument_list|()
return|;
end_return
begin_expr_stmt
unit|}  QGuiGLContext
DECL|function|shareContext
operator|*
name|QGuiGLContext
operator|::
name|shareContext
operator|(
operator|)
specifier|const
block|{
name|Q_D
argument_list|(
specifier|const
name|QGuiGLContext
argument_list|)
block|;
if|if
condition|(
operator|!
name|d
operator|->
name|platformGLContext
condition|)
return|return
literal|0
return|;
end_expr_stmt
begin_return
return|return
name|d
operator|->
name|shareContext
return|;
end_return
begin_comment
unit|}
comment|/*   internal: Needs to have a pointer to qGLContext. But since this is in QtGui we cant   have any type information. */
end_comment
begin_expr_stmt
unit|void
DECL|function|qGLContextHandle
operator|*
name|QGuiGLContext
operator|::
name|qGLContextHandle
operator|(
operator|)
specifier|const
block|{
name|Q_D
argument_list|(
specifier|const
name|QGuiGLContext
argument_list|)
block|;
return|return
name|d
operator|->
name|qGLContextHandle
return|;
block|}
end_expr_stmt
begin_function
DECL|function|setQGLContextHandle
name|void
name|QGuiGLContext
operator|::
name|setQGLContextHandle
parameter_list|(
name|void
modifier|*
name|handle
parameter_list|,
name|void
function_decl|(
modifier|*
name|qGLContextDeleteFunction
function_decl|)
parameter_list|(
name|void
modifier|*
parameter_list|)
parameter_list|)
block|{
name|Q_D
argument_list|(
name|QGuiGLContext
argument_list|)
expr_stmt|;
name|d
operator|->
name|qGLContextHandle
operator|=
name|handle
expr_stmt|;
name|d
operator|->
name|qGLContextDeleteFunction
operator|=
name|qGLContextDeleteFunction
expr_stmt|;
block|}
end_function
begin_function
DECL|function|deleteQGLContext
name|void
name|QGuiGLContext
operator|::
name|deleteQGLContext
parameter_list|()
block|{
name|Q_D
argument_list|(
name|QGuiGLContext
argument_list|)
expr_stmt|;
if|if
condition|(
name|d
operator|->
name|qGLContextDeleteFunction
operator|&&
name|d
operator|->
name|qGLContextHandle
condition|)
block|{
name|d
operator|->
name|qGLContextDeleteFunction
argument_list|(
name|d
operator|->
name|qGLContextHandle
argument_list|)
expr_stmt|;
name|d
operator|->
name|qGLContextDeleteFunction
operator|=
literal|0
expr_stmt|;
name|d
operator|->
name|qGLContextHandle
operator|=
literal|0
expr_stmt|;
block|}
block|}
end_function
end_unit
