begin_unit
begin_comment
comment|/**************************************************************************** ** ** Copyright (C) 2016 The Qt Company Ltd. ** Contact: https://www.qt.io/licensing/ ** ** This file is part of the QtGui module of the Qt Toolkit. ** ** $QT_BEGIN_LICENSE:LGPL$ ** Commercial License Usage ** Licensees holding valid commercial Qt licenses may use this file in ** accordance with the commercial license agreement provided with the ** Software or, alternatively, in accordance with the terms contained in ** a written agreement between you and The Qt Company. For licensing terms ** and conditions see https://www.qt.io/terms-conditions. For further ** information use the contact form at https://www.qt.io/contact-us. ** ** GNU Lesser General Public License Usage ** Alternatively, this file may be used under the terms of the GNU Lesser ** General Public License version 3 as published by the Free Software ** Foundation and appearing in the file LICENSE.LGPL3 included in the ** packaging of this file. Please review the following information to ** ensure the GNU Lesser General Public License version 3 requirements ** will be met: https://www.gnu.org/licenses/lgpl-3.0.html. ** ** GNU General Public License Usage ** Alternatively, this file may be used under the terms of the GNU ** General Public License version 2.0 or (at your option) the GNU General ** Public license version 3 or any later version approved by the KDE Free ** Qt Foundation. The licenses are as published by the Free Software ** Foundation and appearing in the file LICENSE.GPL2 and LICENSE.GPL3 ** included in the packaging of this file. Please review the following ** information to ensure the GNU General Public License requirements will ** be met: https://www.gnu.org/licenses/gpl-2.0.html and ** https://www.gnu.org/licenses/gpl-3.0.html. ** ** $QT_END_LICENSE$ ** ****************************************************************************/
end_comment
begin_ifndef
ifndef|#
directive|ifndef
name|QSCREEN_P_H
end_ifndef
begin_define
DECL|macro|QSCREEN_P_H
define|#
directive|define
name|QSCREEN_P_H
end_define
begin_comment
comment|//
end_comment
begin_comment
comment|//  W A R N I N G
end_comment
begin_comment
comment|//  -------------
end_comment
begin_comment
comment|//
end_comment
begin_comment
comment|// This file is not part of the Qt API.  It exists purely as an
end_comment
begin_comment
comment|// implementation detail.  This header file may change from version to
end_comment
begin_comment
comment|// version without notice, or even be removed.
end_comment
begin_comment
comment|//
end_comment
begin_comment
comment|// We mean it.
end_comment
begin_comment
comment|//
end_comment
begin_include
include|#
directive|include
file|<QtGui/qscreen.h>
end_include
begin_include
include|#
directive|include
file|<qpa/qplatformscreen.h>
end_include
begin_include
include|#
directive|include
file|"qhighdpiscaling_p.h"
end_include
begin_include
include|#
directive|include
file|<QtCore/private/qobject_p.h>
end_include
begin_decl_stmt
name|QT_BEGIN_NAMESPACE
name|class
name|QScreenPrivate
range|:
name|public
name|QObjectPrivate
block|{
name|Q_DECLARE_PUBLIC
argument_list|(
argument|QScreen
argument_list|)
name|public
operator|:
name|QScreenPrivate
argument_list|()
operator|:
name|platformScreen
argument_list|(
literal|0
argument_list|)
block|,
name|orientationUpdateMask
argument_list|(
literal|0
argument_list|)
block|{     }
name|void
name|setPlatformScreen
argument_list|(
name|QPlatformScreen
operator|*
name|screen
argument_list|)
block|;
name|void
name|updateHighDpi
argument_list|()
block|{
name|geometry
operator|=
name|platformScreen
operator|->
name|deviceIndependentGeometry
argument_list|()
block|;
name|availableGeometry
operator|=
name|QHighDpi
operator|::
name|fromNative
argument_list|(
name|platformScreen
operator|->
name|availableGeometry
argument_list|()
argument_list|,
name|QHighDpiScaling
operator|::
name|factor
argument_list|(
name|platformScreen
argument_list|)
argument_list|,
name|geometry
operator|.
name|topLeft
argument_list|()
argument_list|)
block|;     }
name|void
name|updatePrimaryOrientation
argument_list|()
block|;
name|QPlatformScreen
operator|*
name|platformScreen
block|;
name|Qt
operator|::
name|ScreenOrientations
name|orientationUpdateMask
block|;
name|Qt
operator|::
name|ScreenOrientation
name|orientation
block|;
name|Qt
operator|::
name|ScreenOrientation
name|filteredOrientation
block|;
name|Qt
operator|::
name|ScreenOrientation
name|primaryOrientation
block|;
name|QRect
name|geometry
block|;
name|QRect
name|availableGeometry
block|;
name|QDpi
name|logicalDpi
block|;
name|qreal
name|refreshRate
block|; }
decl_stmt|;
end_decl_stmt
begin_macro
name|QT_END_NAMESPACE
end_macro
begin_endif
endif|#
directive|endif
end_endif
begin_comment
comment|// QSCREEN_P_H
end_comment
end_unit
