begin_unit
begin_comment
comment|/**************************************************************************** ** ** Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies). ** Contact: http://www.qt-project.org/legal ** ** This file is part of the test suite of the Qt Toolkit. ** ** $QT_BEGIN_LICENSE:LGPL$ ** Commercial License Usage ** Licensees holding valid commercial Qt licenses may use this file in ** accordance with the commercial license agreement provided with the ** Software or, alternatively, in accordance with the terms contained in ** a written agreement between you and Digia.  For licensing terms and ** conditions see http://qt.digia.com/licensing.  For further information ** use the contact form at http://qt.digia.com/contact-us. ** ** GNU Lesser General Public License Usage ** Alternatively, this file may be used under the terms of the GNU Lesser ** General Public License version 2.1 as published by the Free Software ** Foundation and appearing in the file LICENSE.LGPL included in the ** packaging of this file.  Please review the following information to ** ensure the GNU Lesser General Public License version 2.1 requirements ** will be met: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html. ** ** In addition, as a special exception, Digia gives you certain additional ** rights.  These rights are described in the Digia Qt LGPL Exception ** version 1.1, included in the file LGPL_EXCEPTION.txt in this package. ** ** GNU General Public License Usage ** Alternatively, this file may be used under the terms of the GNU ** General Public License version 3.0 as published by the Free Software ** Foundation and appearing in the file LICENSE.GPL included in the ** packaging of this file.  Please review the following information to ** ensure the GNU General Public License version 3.0 requirements will be ** met: http://www.gnu.org/copyleft/gpl.html. ** ** ** $QT_END_LICENSE$ ** ****************************************************************************/
end_comment
begin_include
include|#
directive|include
file|<QtTest/QtTest>
end_include
begin_include
include|#
directive|include
file|<QtNetwork/qnetworkaccessmanager.h>
end_include
begin_macro
name|QT_USE_NAMESPACE
end_macro
begin_class
DECL|class|tst_QNetworkConfigurationManager
class|class
name|tst_QNetworkConfigurationManager
super|:
specifier|public
name|QObject
block|{
name|Q_OBJECT
private|private
name|slots
private|:
name|void
name|staticsInitialization
parameter_list|()
function_decl|;
block|}
class|;
end_class
begin_function
DECL|function|staticsInitialization
name|void
name|tst_QNetworkConfigurationManager
operator|::
name|staticsInitialization
parameter_list|()
block|{
comment|// This code should not crash. The test was introduced as
comment|// a fix for https://bugreports.qt-project.org/browse/QTBUG-36897
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
literal|2
condition|;
name|i
operator|++
control|)
block|{
name|int
name|argc
init|=
literal|1
decl_stmt|;
specifier|const
name|char
modifier|*
name|testName
init|=
literal|"tst_qnetworkconfigurationmanagerqappless"
decl_stmt|;
name|char
modifier|*
modifier|*
name|argv
init|=
cast|const_cast
argument_list|<
name|char
operator|*
operator|*
argument_list|>
argument_list|(
operator|&
name|testName
argument_list|)
decl_stmt|;
name|QCoreApplication
name|app
argument_list|(
name|argc
argument_list|,
name|argv
argument_list|)
decl_stmt|;
name|QNetworkAccessManager
name|qnam
decl_stmt|;
name|Q_UNUSED
argument_list|(
name|app
argument_list|)
expr_stmt|;
name|Q_UNUSED
argument_list|(
name|qnam
argument_list|)
expr_stmt|;
block|}
name|QVERIFY
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
end_function
begin_macro
name|QTEST_APPLESS_MAIN
argument_list|(
argument|tst_QNetworkConfigurationManager
argument_list|)
end_macro
begin_include
include|#
directive|include
file|"tst_qnetworkconfigurationmanagerqappless.moc"
end_include
end_unit
