begin_unit
begin_comment
comment|/**************************************************************************** ** ** Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies). ** All rights reserved. ** Contact: Nokia Corporation (qt-info@nokia.com) ** ** This file is part of the QtCore module of the Qt Toolkit. ** ** $QT_BEGIN_LICENSE:LGPL$ ** GNU Lesser General Public License Usage ** This file may be used under the terms of the GNU Lesser General Public ** License version 2.1 as published by the Free Software Foundation and ** appearing in the file LICENSE.LGPL included in the packaging of this ** file. Please review the following information to ensure the GNU Lesser ** General Public License version 2.1 requirements will be met: ** http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html. ** ** In addition, as a special exception, Nokia gives you certain additional ** rights. These rights are described in the Nokia Qt LGPL Exception ** version 1.1, included in the file LGPL_EXCEPTION.txt in this package. ** ** GNU General Public License Usage ** Alternatively, this file may be used under the terms of the GNU General ** Public License version 3.0 as published by the Free Software Foundation ** and appearing in the file LICENSE.GPL included in the packaging of this ** file. Please review the following information to ensure the GNU General ** Public License version 3.0 requirements will be met: ** http://www.gnu.org/copyleft/gpl.html. ** ** Other Usage ** Alternatively, this file may be used in accordance with the terms and ** conditions contained in a signed written agreement between you and Nokia. ** ** ** ** ** ** $QT_END_LICENSE$ ** ****************************************************************************/
end_comment
begin_ifndef
ifndef|#
directive|ifndef
name|QSCOPEDVALUEROLLBACK_H
end_ifndef
begin_define
DECL|macro|QSCOPEDVALUEROLLBACK_H
define|#
directive|define
name|QSCOPEDVALUEROLLBACK_H
end_define
begin_include
include|#
directive|include
file|<QtCore/qglobal.h>
end_include
begin_decl_stmt
name|QT_BEGIN_HEADER
name|QT_BEGIN_NAMESPACE
DECL|function|QT_MODULE
name|QT_MODULE
argument_list|(
name|Core
argument_list|)
name|template
decl|<
name|typename
name|T
decl|>
name|class
name|QScopedValueRollback
block|{
name|public
label|:
name|QScopedValueRollback
argument_list|(
name|T
operator|&
name|var
argument_list|)
operator|:
name|varRef
argument_list|(
argument|var
argument_list|)
block|{
name|oldValue
operator|=
name|varRef
block|;     }
operator|~
name|QScopedValueRollback
argument_list|()
block|{
name|varRef
operator|=
name|oldValue
block|;     }
name|void
name|commit
argument_list|()
block|{
name|oldValue
operator|=
name|varRef
block|;     }
name|private
operator|:
name|T
operator|&
name|varRef
expr_stmt|;
name|T
name|oldValue
decl_stmt|;
name|Q_DISABLE_COPY
argument_list|(
argument|QScopedValueRollback
argument_list|)
block|}
end_decl_stmt
begin_empty_stmt
empty_stmt|;
end_empty_stmt
begin_expr_stmt
name|QT_END_NAMESPACE
name|QT_END_HEADER
end_expr_stmt
begin_endif
endif|#
directive|endif
end_endif
begin_comment
comment|// QSCOPEDVALUEROLLBACK_H
end_comment
end_unit
