begin_unit
begin_comment
comment|/**************************************************************************** ** ** Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies). ** All rights reserved. ** Contact: Nokia Corporation (qt-info@nokia.com) ** ** This file is part of the plugins of the Qt Toolkit. ** ** $QT_BEGIN_LICENSE:LGPL$ ** GNU Lesser General Public License Usage ** This file may be used under the terms of the GNU Lesser General Public ** License version 2.1 as published by the Free Software Foundation and ** appearing in the file LICENSE.LGPL included in the packaging of this ** file. Please review the following information to ensure the GNU Lesser ** General Public License version 2.1 requirements will be met: ** http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html. ** ** In addition, as a special exception, Nokia gives you certain additional ** rights. These rights are described in the Nokia Qt LGPL Exception ** version 1.1, included in the file LGPL_EXCEPTION.txt in this package. ** ** GNU General Public License Usage ** Alternatively, this file may be used under the terms of the GNU General ** Public License version 3.0 as published by the Free Software Foundation ** and appearing in the file LICENSE.GPL included in the packaging of this ** file. Please review the following information to ensure the GNU General ** Public License version 3.0 requirements will be met: ** http://www.gnu.org/copyleft/gpl.html. ** ** Other Usage ** Alternatively, this file may be used in accordance with the terms and ** conditions contained in a signed written agreement between you and Nokia. ** ** ** ** ** ** $QT_END_LICENSE$ ** ****************************************************************************/
end_comment
begin_include
include|#
directive|include
file|"qnativewifiengine.h"
end_include
begin_include
include|#
directive|include
file|"platformdefs.h"
end_include
begin_include
include|#
directive|include
file|<QtCore/qmutex.h>
end_include
begin_include
include|#
directive|include
file|<QtCore/private/qmutexpool_p.h>
end_include
begin_include
include|#
directive|include
file|<QtCore/qlibrary.h>
end_include
begin_include
include|#
directive|include
file|<QtNetwork/private/qbearerplugin_p.h>
end_include
begin_include
include|#
directive|include
file|<QtCore/qdebug.h>
end_include
begin_ifndef
ifndef|#
directive|ifndef
name|QT_NO_BEARERMANAGEMENT
end_ifndef
begin_function
name|QT_BEGIN_NAMESPACE
DECL|function|resolveLibrary
specifier|static
name|void
name|resolveLibrary
parameter_list|()
block|{
specifier|static
specifier|volatile
name|bool
name|triedResolve
init|=
literal|false
decl_stmt|;
if|if
condition|(
operator|!
name|triedResolve
condition|)
block|{
ifndef|#
directive|ifndef
name|QT_NO_THREAD
name|QMutexLocker
name|locker
argument_list|(
name|QMutexPool
operator|::
name|globalInstanceGet
argument_list|(
operator|&
name|local_WlanOpenHandle
argument_list|)
argument_list|)
decl_stmt|;
endif|#
directive|endif
if|if
condition|(
operator|!
name|triedResolve
condition|)
block|{
name|local_WlanOpenHandle
operator|=
operator|(
name|WlanOpenHandleProto
operator|)
name|QLibrary
operator|::
name|resolve
argument_list|(
name|QLatin1String
argument_list|(
literal|"wlanapi.dll"
argument_list|)
argument_list|,
literal|"WlanOpenHandle"
argument_list|)
expr_stmt|;
name|local_WlanRegisterNotification
operator|=
operator|(
name|WlanRegisterNotificationProto
operator|)
name|QLibrary
operator|::
name|resolve
argument_list|(
name|QLatin1String
argument_list|(
literal|"wlanapi.dll"
argument_list|)
argument_list|,
literal|"WlanRegisterNotification"
argument_list|)
expr_stmt|;
name|local_WlanEnumInterfaces
operator|=
operator|(
name|WlanEnumInterfacesProto
operator|)
name|QLibrary
operator|::
name|resolve
argument_list|(
name|QLatin1String
argument_list|(
literal|"wlanapi.dll"
argument_list|)
argument_list|,
literal|"WlanEnumInterfaces"
argument_list|)
expr_stmt|;
name|local_WlanGetAvailableNetworkList
operator|=
operator|(
name|WlanGetAvailableNetworkListProto
operator|)
name|QLibrary
operator|::
name|resolve
argument_list|(
name|QLatin1String
argument_list|(
literal|"wlanapi.dll"
argument_list|)
argument_list|,
literal|"WlanGetAvailableNetworkList"
argument_list|)
expr_stmt|;
name|local_WlanQueryInterface
operator|=
operator|(
name|WlanQueryInterfaceProto
operator|)
name|QLibrary
operator|::
name|resolve
argument_list|(
name|QLatin1String
argument_list|(
literal|"wlanapi.dll"
argument_list|)
argument_list|,
literal|"WlanQueryInterface"
argument_list|)
expr_stmt|;
name|local_WlanConnect
operator|=
operator|(
name|WlanConnectProto
operator|)
name|QLibrary
operator|::
name|resolve
argument_list|(
name|QLatin1String
argument_list|(
literal|"wlanapi.dll"
argument_list|)
argument_list|,
literal|"WlanConnect"
argument_list|)
expr_stmt|;
name|local_WlanDisconnect
operator|=
operator|(
name|WlanDisconnectProto
operator|)
name|QLibrary
operator|::
name|resolve
argument_list|(
name|QLatin1String
argument_list|(
literal|"wlanapi.dll"
argument_list|)
argument_list|,
literal|"WlanDisconnect"
argument_list|)
expr_stmt|;
name|local_WlanScan
operator|=
operator|(
name|WlanScanProto
operator|)
name|QLibrary
operator|::
name|resolve
argument_list|(
name|QLatin1String
argument_list|(
literal|"wlanapi.dll"
argument_list|)
argument_list|,
literal|"WlanScan"
argument_list|)
expr_stmt|;
name|local_WlanFreeMemory
operator|=
operator|(
name|WlanFreeMemoryProto
operator|)
name|QLibrary
operator|::
name|resolve
argument_list|(
name|QLatin1String
argument_list|(
literal|"wlanapi.dll"
argument_list|)
argument_list|,
literal|"WlanFreeMemory"
argument_list|)
expr_stmt|;
name|local_WlanCloseHandle
operator|=
operator|(
name|WlanCloseHandleProto
operator|)
name|QLibrary
operator|::
name|resolve
argument_list|(
name|QLatin1String
argument_list|(
literal|"wlanapi.dll"
argument_list|)
argument_list|,
literal|"WlanCloseHandle"
argument_list|)
expr_stmt|;
name|triedResolve
operator|=
literal|true
expr_stmt|;
block|}
block|}
block|}
end_function
begin_class
DECL|class|QNativeWifiEnginePlugin
class|class
name|QNativeWifiEnginePlugin
super|:
specifier|public
name|QBearerEnginePlugin
block|{
public|public:
name|QNativeWifiEnginePlugin
parameter_list|()
constructor_decl|;
name|~
name|QNativeWifiEnginePlugin
parameter_list|()
destructor_decl|;
name|QStringList
name|keys
parameter_list|()
specifier|const
function_decl|;
name|QBearerEngine
modifier|*
name|create
parameter_list|(
specifier|const
name|QString
modifier|&
name|key
parameter_list|)
specifier|const
function_decl|;
block|}
class|;
end_class
begin_constructor
DECL|function|QNativeWifiEnginePlugin
name|QNativeWifiEnginePlugin
operator|::
name|QNativeWifiEnginePlugin
parameter_list|()
block|{ }
end_constructor
begin_destructor
DECL|function|~QNativeWifiEnginePlugin
name|QNativeWifiEnginePlugin
operator|::
name|~
name|QNativeWifiEnginePlugin
parameter_list|()
block|{ }
end_destructor
begin_function
DECL|function|keys
name|QStringList
name|QNativeWifiEnginePlugin
operator|::
name|keys
parameter_list|()
specifier|const
block|{
return|return
name|QStringList
argument_list|()
operator|<<
name|QLatin1String
argument_list|(
literal|"nativewifi"
argument_list|)
return|;
block|}
end_function
begin_function
DECL|function|create
name|QBearerEngine
modifier|*
name|QNativeWifiEnginePlugin
operator|::
name|create
parameter_list|(
specifier|const
name|QString
modifier|&
name|key
parameter_list|)
specifier|const
block|{
if|if
condition|(
name|key
operator|!=
name|QLatin1String
argument_list|(
literal|"nativewifi"
argument_list|)
condition|)
return|return
literal|0
return|;
name|resolveLibrary
argument_list|()
expr_stmt|;
comment|// native wifi dll not available
if|if
condition|(
operator|!
name|local_WlanOpenHandle
condition|)
return|return
literal|0
return|;
name|QNativeWifiEngine
modifier|*
name|engine
init|=
operator|new
name|QNativeWifiEngine
decl_stmt|;
comment|// could not initialise subsystem
if|if
condition|(
name|engine
operator|&&
operator|!
name|engine
operator|->
name|available
argument_list|()
condition|)
block|{
operator|delete
name|engine
expr_stmt|;
return|return
literal|0
return|;
block|}
return|return
name|engine
return|;
block|}
end_function
begin_macro
name|Q_EXPORT_STATIC_PLUGIN
argument_list|(
argument|QNativeWifiEnginePlugin
argument_list|)
end_macro
begin_macro
name|Q_EXPORT_PLUGIN2
argument_list|(
argument|qnativewifibearer
argument_list|,
argument|QNativeWifiEnginePlugin
argument_list|)
end_macro
begin_macro
name|QT_END_NAMESPACE
end_macro
begin_endif
endif|#
directive|endif
end_endif
begin_comment
comment|// QT_NO_BEARERMANAGEMENT
end_comment
end_unit
