begin_unit
begin_comment
comment|/******************************************************************************** ** Form generated from reading UI file 'myform.ui' ** ** Created by: Qt User Interface Compiler version 5.0.0 ** ** WARNING! All changes made in this file will be lost when recompiling UI file! ********************************************************************************/
end_comment
begin_ifndef
ifndef|#
directive|ifndef
name|MYFORM_H
end_ifndef
begin_define
DECL|macro|MYFORM_H
define|#
directive|define
name|MYFORM_H
end_define
begin_include
include|#
directive|include
file|<QtCore/QVariant>
end_include
begin_include
include|#
directive|include
file|<QtWidgets/QAction>
end_include
begin_include
include|#
directive|include
file|<QtWidgets/QApplication>
end_include
begin_include
include|#
directive|include
file|<QtWidgets/QButtonGroup>
end_include
begin_include
include|#
directive|include
file|<QtWidgets/QCheckBox>
end_include
begin_include
include|#
directive|include
file|<QtWidgets/QGridLayout>
end_include
begin_include
include|#
directive|include
file|<QtWidgets/QGroupBox>
end_include
begin_include
include|#
directive|include
file|<QtWidgets/QHeaderView>
end_include
begin_include
include|#
directive|include
file|<QtWidgets/QRadioButton>
end_include
begin_include
include|#
directive|include
file|<QtWidgets/QSpacerItem>
end_include
begin_include
include|#
directive|include
file|<QtWidgets/QVBoxLayout>
end_include
begin_include
include|#
directive|include
file|<QtWidgets/QWidget>
end_include
begin_decl_stmt
name|QT_BEGIN_NAMESPACE
name|class
name|Ui_Form
block|{
name|public
label|:
name|QVBoxLayout
modifier|*
name|vboxLayout
decl_stmt|;
name|QGroupBox
modifier|*
name|groupBox
decl_stmt|;
name|QGridLayout
modifier|*
name|gridLayout
decl_stmt|;
name|QRadioButton
modifier|*
name|radioButton_2
decl_stmt|;
name|QRadioButton
modifier|*
name|radioButton
decl_stmt|;
name|QCheckBox
modifier|*
name|checkBox_2
decl_stmt|;
name|QSpacerItem
modifier|*
name|spacerItem
decl_stmt|;
name|QCheckBox
modifier|*
name|checkBox
decl_stmt|;
name|QRadioButton
modifier|*
name|radioButton_2_2
decl_stmt|;
name|QRadioButton
modifier|*
name|radioButton_3
decl_stmt|;
name|QRadioButton
modifier|*
name|radioButton_4
decl_stmt|;
name|QCheckBox
modifier|*
name|checkBox_3
decl_stmt|;
name|QCheckBox
modifier|*
name|checkBox_4
decl_stmt|;
name|void
name|setupUi
parameter_list|(
name|QWidget
modifier|*
name|Form
parameter_list|)
block|{
if|if
condition|(
name|Form
operator|->
name|objectName
argument_list|()
operator|.
name|isEmpty
argument_list|()
condition|)
name|Form
operator|->
name|setObjectName
argument_list|(
name|QStringLiteral
argument_list|(
literal|"Form"
argument_list|)
argument_list|)
expr_stmt|;
name|Form
operator|->
name|resize
argument_list|(
literal|258
argument_list|,
literal|224
argument_list|)
expr_stmt|;
name|vboxLayout
operator|=
name|new
name|QVBoxLayout
argument_list|(
name|Form
argument_list|)
expr_stmt|;
ifndef|#
directive|ifndef
name|Q_OS_MAC
name|vboxLayout
operator|->
name|setSpacing
argument_list|(
literal|6
argument_list|)
expr_stmt|;
endif|#
directive|endif
name|vboxLayout
operator|->
name|setContentsMargins
argument_list|(
literal|8
argument_list|,
literal|8
argument_list|,
literal|8
argument_list|,
literal|8
argument_list|)
expr_stmt|;
name|vboxLayout
operator|->
name|setObjectName
argument_list|(
name|QStringLiteral
argument_list|(
literal|"vboxLayout"
argument_list|)
argument_list|)
expr_stmt|;
name|groupBox
operator|=
name|new
name|QGroupBox
argument_list|(
name|Form
argument_list|)
expr_stmt|;
name|groupBox
operator|->
name|setObjectName
argument_list|(
name|QStringLiteral
argument_list|(
literal|"groupBox"
argument_list|)
argument_list|)
expr_stmt|;
name|gridLayout
operator|=
name|new
name|QGridLayout
argument_list|(
name|groupBox
argument_list|)
expr_stmt|;
ifndef|#
directive|ifndef
name|Q_OS_MAC
name|gridLayout
operator|->
name|setSpacing
argument_list|(
literal|6
argument_list|)
expr_stmt|;
endif|#
directive|endif
name|gridLayout
operator|->
name|setContentsMargins
argument_list|(
literal|8
argument_list|,
literal|8
argument_list|,
literal|8
argument_list|,
literal|8
argument_list|)
expr_stmt|;
name|gridLayout
operator|->
name|setObjectName
argument_list|(
name|QStringLiteral
argument_list|(
literal|"gridLayout"
argument_list|)
argument_list|)
expr_stmt|;
name|radioButton_2
operator|=
name|new
name|QRadioButton
argument_list|(
name|groupBox
argument_list|)
expr_stmt|;
name|radioButton_2
operator|->
name|setObjectName
argument_list|(
name|QStringLiteral
argument_list|(
literal|"radioButton_2"
argument_list|)
argument_list|)
expr_stmt|;
name|gridLayout
operator|->
name|addWidget
argument_list|(
name|radioButton_2
argument_list|,
literal|1
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|radioButton
operator|=
name|new
name|QRadioButton
argument_list|(
name|groupBox
argument_list|)
expr_stmt|;
name|radioButton
operator|->
name|setObjectName
argument_list|(
name|QStringLiteral
argument_list|(
literal|"radioButton"
argument_list|)
argument_list|)
expr_stmt|;
name|radioButton
operator|->
name|setChecked
argument_list|(
name|true
argument_list|)
expr_stmt|;
name|gridLayout
operator|->
name|addWidget
argument_list|(
name|radioButton
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|checkBox_2
operator|=
name|new
name|QCheckBox
argument_list|(
name|groupBox
argument_list|)
expr_stmt|;
name|checkBox_2
operator|->
name|setObjectName
argument_list|(
name|QStringLiteral
argument_list|(
literal|"checkBox_2"
argument_list|)
argument_list|)
expr_stmt|;
name|checkBox_2
operator|->
name|setChecked
argument_list|(
name|true
argument_list|)
expr_stmt|;
name|gridLayout
operator|->
name|addWidget
argument_list|(
name|checkBox_2
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|spacerItem
operator|=
name|new
name|QSpacerItem
argument_list|(
literal|20
argument_list|,
literal|40
argument_list|,
name|QSizePolicy
operator|::
name|Minimum
argument_list|,
name|QSizePolicy
operator|::
name|Expanding
argument_list|)
expr_stmt|;
name|gridLayout
operator|->
name|addItem
argument_list|(
name|spacerItem
argument_list|,
literal|5
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|checkBox
operator|=
name|new
name|QCheckBox
argument_list|(
name|groupBox
argument_list|)
expr_stmt|;
name|checkBox
operator|->
name|setObjectName
argument_list|(
name|QStringLiteral
argument_list|(
literal|"checkBox"
argument_list|)
argument_list|)
expr_stmt|;
name|gridLayout
operator|->
name|addWidget
argument_list|(
name|checkBox
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|radioButton_2_2
operator|=
name|new
name|QRadioButton
argument_list|(
name|groupBox
argument_list|)
expr_stmt|;
name|radioButton_2_2
operator|->
name|setObjectName
argument_list|(
name|QStringLiteral
argument_list|(
literal|"radioButton_2_2"
argument_list|)
argument_list|)
expr_stmt|;
name|gridLayout
operator|->
name|addWidget
argument_list|(
name|radioButton_2_2
argument_list|,
literal|2
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|radioButton_3
operator|=
name|new
name|QRadioButton
argument_list|(
name|groupBox
argument_list|)
expr_stmt|;
name|radioButton_3
operator|->
name|setObjectName
argument_list|(
name|QStringLiteral
argument_list|(
literal|"radioButton_3"
argument_list|)
argument_list|)
expr_stmt|;
name|gridLayout
operator|->
name|addWidget
argument_list|(
name|radioButton_3
argument_list|,
literal|3
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|radioButton_4
operator|=
name|new
name|QRadioButton
argument_list|(
name|groupBox
argument_list|)
expr_stmt|;
name|radioButton_4
operator|->
name|setObjectName
argument_list|(
name|QStringLiteral
argument_list|(
literal|"radioButton_4"
argument_list|)
argument_list|)
expr_stmt|;
name|gridLayout
operator|->
name|addWidget
argument_list|(
name|radioButton_4
argument_list|,
literal|4
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|checkBox_3
operator|=
name|new
name|QCheckBox
argument_list|(
name|groupBox
argument_list|)
expr_stmt|;
name|checkBox_3
operator|->
name|setObjectName
argument_list|(
name|QStringLiteral
argument_list|(
literal|"checkBox_3"
argument_list|)
argument_list|)
expr_stmt|;
name|gridLayout
operator|->
name|addWidget
argument_list|(
name|checkBox_3
argument_list|,
literal|2
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|checkBox_4
operator|=
name|new
name|QCheckBox
argument_list|(
name|groupBox
argument_list|)
expr_stmt|;
name|checkBox_4
operator|->
name|setObjectName
argument_list|(
name|QStringLiteral
argument_list|(
literal|"checkBox_4"
argument_list|)
argument_list|)
expr_stmt|;
name|checkBox_4
operator|->
name|setChecked
argument_list|(
name|true
argument_list|)
expr_stmt|;
name|gridLayout
operator|->
name|addWidget
argument_list|(
name|checkBox_4
argument_list|,
literal|3
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|vboxLayout
operator|->
name|addWidget
argument_list|(
name|groupBox
argument_list|)
expr_stmt|;
name|retranslateUi
argument_list|(
name|Form
argument_list|)
expr_stmt|;
name|QMetaObject
operator|::
name|connectSlotsByName
argument_list|(
name|Form
argument_list|)
expr_stmt|;
block|}
comment|// setupUi
name|void
name|retranslateUi
parameter_list|(
name|QWidget
modifier|*
name|Form
parameter_list|)
block|{
name|Form
operator|->
name|setWindowTitle
argument_list|(
name|QApplication
operator|::
name|translate
argument_list|(
literal|"Form"
argument_list|,
literal|"Export Document"
argument_list|,
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|groupBox
operator|->
name|setTitle
argument_list|(
name|QApplication
operator|::
name|translate
argument_list|(
literal|"Form"
argument_list|,
literal|"Export Options"
argument_list|,
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|radioButton_2
operator|->
name|setText
argument_list|(
name|QApplication
operator|::
name|translate
argument_list|(
literal|"Form"
argument_list|,
literal|"&DocBook"
argument_list|,
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|radioButton
operator|->
name|setText
argument_list|(
name|QApplication
operator|::
name|translate
argument_list|(
literal|"Form"
argument_list|,
literal|"&LaTeX"
argument_list|,
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|checkBox_2
operator|->
name|setText
argument_list|(
name|QApplication
operator|::
name|translate
argument_list|(
literal|"Form"
argument_list|,
literal|"Include p&ictures"
argument_list|,
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|checkBox
operator|->
name|setText
argument_list|(
name|QApplication
operator|::
name|translate
argument_list|(
literal|"Form"
argument_list|,
literal|"&Compress"
argument_list|,
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|radioButton_2_2
operator|->
name|setText
argument_list|(
name|QApplication
operator|::
name|translate
argument_list|(
literal|"Form"
argument_list|,
literal|"&HTML"
argument_list|,
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|radioButton_3
operator|->
name|setText
argument_list|(
name|QApplication
operator|::
name|translate
argument_list|(
literal|"Form"
argument_list|,
literal|"&PostScript"
argument_list|,
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|radioButton_4
operator|->
name|setText
argument_list|(
name|QApplication
operator|::
name|translate
argument_list|(
literal|"Form"
argument_list|,
literal|"PD&F"
argument_list|,
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|checkBox_3
operator|->
name|setText
argument_list|(
name|QApplication
operator|::
name|translate
argument_list|(
literal|"Form"
argument_list|,
literal|"Include&metadata"
argument_list|,
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|checkBox_4
operator|->
name|setText
argument_list|(
name|QApplication
operator|::
name|translate
argument_list|(
literal|"Form"
argument_list|,
literal|"Create inde&x"
argument_list|,
literal|0
argument_list|)
argument_list|)
expr_stmt|;
block|}
comment|// retranslateUi
block|}
end_decl_stmt
begin_empty_stmt
empty_stmt|;
end_empty_stmt
begin_decl_stmt
name|namespace
name|Ui
block|{
name|class
name|Form
range|:
name|public
name|Ui_Form
block|{}
decl_stmt|;
block|}
end_decl_stmt
begin_comment
comment|// namespace Ui
end_comment
begin_macro
name|QT_END_NAMESPACE
end_macro
begin_endif
endif|#
directive|endif
end_endif
begin_comment
comment|// MYFORM_H
end_comment
end_unit
