begin_unit
begin_comment
comment|/**************************************************************************** ** ** Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies). ** Contact: http://www.qt-project.org/ ** ** This file is part of the plugins of the Qt Toolkit. ** ** $QT_BEGIN_LICENSE:LGPL$ ** GNU Lesser General Public License Usage ** This file may be used under the terms of the GNU Lesser General Public ** License version 2.1 as published by the Free Software Foundation and ** appearing in the file LICENSE.LGPL included in the packaging of this ** file. Please review the following information to ensure the GNU Lesser ** General Public License version 2.1 requirements will be met: ** http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html. ** ** In addition, as a special exception, Nokia gives you certain additional ** rights. These rights are described in the Nokia Qt LGPL Exception ** version 1.1, included in the file LGPL_EXCEPTION.txt in this package. ** ** GNU General Public License Usage ** Alternatively, this file may be used under the terms of the GNU General ** Public License version 3.0 as published by the Free Software Foundation ** and appearing in the file LICENSE.GPL included in the packaging of this ** file. Please review the following information to ensure the GNU General ** Public License version 3.0 requirements will be met: ** http://www.gnu.org/copyleft/gpl.html. ** ** Other Usage ** Alternatively, this file may be used in accordance with the terms and ** conditions contained in a signed written agreement between you and Nokia. ** ** ** ** ** ** ** $QT_END_LICENSE$ ** ****************************************************************************/
end_comment
begin_ifndef
ifndef|#
directive|ifndef
name|QOPENKODEEVENTLOOPINTEGRATION_H
end_ifndef
begin_define
DECL|macro|QOPENKODEEVENTLOOPINTEGRATION_H
define|#
directive|define
name|QOPENKODEEVENTLOOPINTEGRATION_H
end_define
begin_include
include|#
directive|include
file|<QtGui/QPlatformEventLoopIntegration>
end_include
begin_decl_stmt
DECL|variable|KDThread
name|class
name|KDThread
decl_stmt|;
end_decl_stmt
begin_decl_stmt
DECL|variable|KDEvent
name|class
name|KDEvent
decl_stmt|;
end_decl_stmt
begin_decl_stmt
name|QT_BEGIN_HEADER
name|QT_BEGIN_NAMESPACE
name|class
name|QOpenKODEEventLoopIntegration
range|:
name|public
name|QPlatformEventLoopIntegration
block|{
name|public
operator|:
name|QOpenKODEEventLoopIntegration
argument_list|()
block|;
name|void
name|startEventLoop
argument_list|()
block|;
name|void
name|quitEventLoop
argument_list|()
block|;
name|void
name|qtNeedsToProcessEvents
argument_list|()
block|;
name|void
name|processInputEvent
argument_list|(
specifier|const
name|KDEvent
operator|*
name|event
argument_list|)
block|;
name|private
operator|:
name|bool
name|m_quit
block|;
name|KDThread
operator|*
name|m_kdThread
block|; }
decl_stmt|;
end_decl_stmt
begin_expr_stmt
name|QT_END_NAMESPACE
name|QT_END_HEADER
end_expr_stmt
begin_endif
endif|#
directive|endif
end_endif
begin_comment
comment|// QOPENKODEEVENTLOOPINTEGRATION_H
end_comment
end_unit
