begin_unit
begin_comment
comment|/**************************************************************************** ** ** Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies). ** Contact: http://www.qt-project.org/legal ** ** This file is part of the QtGui module of the Qt Toolkit. ** ** $QT_BEGIN_LICENSE:LGPL$ ** Commercial License Usage ** Licensees holding valid commercial Qt licenses may use this file in ** accordance with the commercial license agreement provided with the ** Software or, alternatively, in accordance with the terms contained in ** a written agreement between you and Digia.  For licensing terms and ** conditions see http://qt.digia.com/licensing.  For further information ** use the contact form at http://qt.digia.com/contact-us. ** ** GNU Lesser General Public License Usage ** Alternatively, this file may be used under the terms of the GNU Lesser ** General Public License version 2.1 as published by the Free Software ** Foundation and appearing in the file LICENSE.LGPL included in the ** packaging of this file.  Please review the following information to ** ensure the GNU Lesser General Public License version 2.1 requirements ** will be met: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html. ** ** In addition, as a special exception, Digia gives you certain additional ** rights.  These rights are described in the Digia Qt LGPL Exception ** version 1.1, included in the file LGPL_EXCEPTION.txt in this package. ** ** GNU General Public License Usage ** Alternatively, this file may be used under the terms of the GNU ** General Public License version 3.0 as published by the Free Software ** Foundation and appearing in the file LICENSE.GPL included in the ** packaging of this file.  Please review the following information to ** ensure the GNU General Public License version 3.0 requirements will be ** met: http://www.gnu.org/copyleft/gpl.html. ** ** ** $QT_END_LICENSE$ ** ****************************************************************************/
end_comment
begin_ifndef
ifndef|#
directive|ifndef
name|QBLITTABLE_P_H
end_ifndef
begin_define
DECL|macro|QBLITTABLE_P_H
define|#
directive|define
name|QBLITTABLE_P_H
end_define
begin_include
include|#
directive|include
file|<QtCore/qsize.h>
end_include
begin_include
include|#
directive|include
file|<QtGui/private/qpixmap_blitter_p.h>
end_include
begin_ifndef
ifndef|#
directive|ifndef
name|QT_NO_BLITTABLE
end_ifndef
begin_decl_stmt
name|QT_BEGIN_NAMESPACE
DECL|variable|QImage
name|class
name|QImage
decl_stmt|;
end_decl_stmt
begin_decl_stmt
DECL|variable|QBlittablePrivate
name|class
name|QBlittablePrivate
decl_stmt|;
end_decl_stmt
begin_decl_stmt
name|class
name|Q_GUI_EXPORT
name|QBlittable
block|{
name|Q_DECLARE_PRIVATE
argument_list|(
name|QBlittable
argument_list|)
expr_stmt|;
name|public
label|:
enum|enum
name|Capability
block|{
name|SolidRectCapability
init|=
literal|0x0001
block|,
name|SourcePixmapCapability
init|=
literal|0x0002
block|,
name|SourceOverPixmapCapability
init|=
literal|0x0004
block|,
name|SourceOverScaledPixmapCapability
init|=
literal|0x0008
block|,
name|AlphaFillRectCapability
init|=
literal|0x0010
block|,
name|OpacityPixmapCapability
init|=
literal|0x0020
block|,
comment|// Internal ones
name|OutlineCapability
init|=
literal|0x0001000
block|}
enum|;
name|Q_DECLARE_FLAGS
argument_list|(
name|Capabilities
argument_list|,
name|Capability
argument_list|)
expr_stmt|;
name|QBlittable
argument_list|(
argument|const QSize&size
argument_list|,
argument|Capabilities caps
argument_list|)
empty_stmt|;
name|virtual
operator|~
name|QBlittable
argument_list|()
expr_stmt|;
name|Capabilities
name|capabilities
argument_list|()
specifier|const
expr_stmt|;
name|QSize
name|size
argument_list|()
specifier|const
expr_stmt|;
name|virtual
name|void
name|fillRect
parameter_list|(
specifier|const
name|QRectF
modifier|&
name|rect
parameter_list|,
specifier|const
name|QColor
modifier|&
name|color
parameter_list|)
init|=
literal|0
function_decl|;
name|virtual
name|void
name|drawPixmap
parameter_list|(
specifier|const
name|QRectF
modifier|&
name|rect
parameter_list|,
specifier|const
name|QPixmap
modifier|&
name|pixmap
parameter_list|,
specifier|const
name|QRectF
modifier|&
name|subrect
parameter_list|)
init|=
literal|0
function_decl|;
name|virtual
name|void
name|alphaFillRect
argument_list|(
specifier|const
name|QRectF
operator|&
name|rect
argument_list|,
specifier|const
name|QColor
operator|&
name|color
argument_list|,
name|QPainter
operator|::
name|CompositionMode
name|cmode
argument_list|)
block|{
name|Q_UNUSED
argument_list|(
name|rect
argument_list|)
expr_stmt|;
name|Q_UNUSED
argument_list|(
name|color
argument_list|)
expr_stmt|;
name|Q_UNUSED
argument_list|(
name|cmode
argument_list|)
expr_stmt|;
name|qWarning
argument_list|(
literal|"Please implement alphaFillRect function in your platform or remove AlphaFillRectCapability from it"
argument_list|)
expr_stmt|;
block|}
name|virtual
name|void
name|drawPixmapOpacity
argument_list|(
specifier|const
name|QRectF
operator|&
name|rect
argument_list|,
specifier|const
name|QPixmap
operator|&
name|pixmap
argument_list|,
specifier|const
name|QRectF
operator|&
name|subrect
argument_list|,
name|QPainter
operator|::
name|CompositionMode
name|cmode
argument_list|,
name|qreal
name|opacity
argument_list|)
block|{
name|Q_UNUSED
argument_list|(
name|rect
argument_list|)
expr_stmt|;
name|Q_UNUSED
argument_list|(
name|pixmap
argument_list|)
expr_stmt|;
name|Q_UNUSED
argument_list|(
name|subrect
argument_list|)
expr_stmt|;
name|Q_UNUSED
argument_list|(
name|cmode
argument_list|)
expr_stmt|;
name|Q_UNUSED
argument_list|(
name|opacity
argument_list|)
expr_stmt|;
name|qWarning
argument_list|(
literal|"Please implement drawPixmapOpacity function in your platform or remove OpacityPixmapCapability from it"
argument_list|)
expr_stmt|;
block|}
name|QImage
modifier|*
name|lock
parameter_list|()
function_decl|;
name|void
name|unlock
parameter_list|()
function_decl|;
name|bool
name|isLocked
argument_list|()
specifier|const
expr_stmt|;
name|protected
label|:
name|virtual
name|QImage
modifier|*
name|doLock
parameter_list|()
init|=
literal|0
function_decl|;
name|virtual
name|void
name|doUnlock
parameter_list|()
init|=
literal|0
function_decl|;
name|QBlittablePrivate
modifier|*
name|d_ptr
decl_stmt|;
block|}
end_decl_stmt
begin_empty_stmt
empty_stmt|;
end_empty_stmt
begin_macro
name|QT_END_NAMESPACE
end_macro
begin_endif
endif|#
directive|endif
end_endif
begin_comment
comment|//QT_NO_BLITTABLE
end_comment
begin_endif
endif|#
directive|endif
end_endif
begin_comment
comment|//QBLITTABLE_P_H
end_comment
end_unit
