begin_unit
begin_comment
comment|/**************************************************************************** ** ** Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies). ** Contact: http://www.qt-project.org/legal ** ** This file is part of the plugins of the Qt Toolkit. ** ** $QT_BEGIN_LICENSE:LGPL$ ** Commercial License Usage ** Licensees holding valid commercial Qt licenses may use this file in ** accordance with the commercial license agreement provided with the ** Software or, alternatively, in accordance with the terms contained in ** a written agreement between you and Digia.  For licensing terms and ** conditions see http://qt.digia.com/licensing.  For further information ** use the contact form at http://qt.digia.com/contact-us. ** ** GNU Lesser General Public License Usage ** Alternatively, this file may be used under the terms of the GNU Lesser ** General Public License version 2.1 as published by the Free Software ** Foundation and appearing in the file LICENSE.LGPL included in the ** packaging of this file.  Please review the following information to ** ensure the GNU Lesser General Public License version 2.1 requirements ** will be met: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html. ** ** In addition, as a special exception, Digia gives you certain additional ** rights.  These rights are described in the Digia Qt LGPL Exception ** version 1.1, included in the file LGPL_EXCEPTION.txt in this package. ** ** GNU General Public License Usage ** Alternatively, this file may be used under the terms of the GNU ** General Public License version 3.0 as published by the Free Software ** Foundation and appearing in the file LICENSE.GPL included in the ** packaging of this file.  Please review the following information to ** ensure the GNU General Public License version 3.0 requirements will be ** met: http://www.gnu.org/copyleft/gpl.html. ** ** ** $QT_END_LICENSE$ ** ****************************************************************************/
end_comment
begin_ifndef
ifndef|#
directive|ifndef
name|QKMSUDEVLISTENER_H
end_ifndef
begin_define
DECL|macro|QKMSUDEVLISTENER_H
define|#
directive|define
name|QKMSUDEVLISTENER_H
end_define
begin_include
include|#
directive|include
file|<QObject>
end_include
begin_include
include|#
directive|include
file|<QMap>
end_include
begin_include
include|#
directive|include
file|<QList>
end_include
begin_include
include|#
directive|include
file|<QPointer>
end_include
begin_include
include|#
directive|include
file|<QString>
end_include
begin_include
include|#
directive|include
file|<qkmsudevhandler.h>
end_include
begin_include
include|#
directive|include
file|<libudev.h>
end_include
begin_decl_stmt
name|QT_BEGIN_NAMESPACE
name|class
name|QKmsUdevListener
range|:
name|public
name|QObject
block|{
name|Q_OBJECT
name|public
operator|:
name|QKmsUdevListener
argument_list|(
name|QObject
operator|*
name|parent
operator|=
literal|0
argument_list|)
block|;
operator|~
name|QKmsUdevListener
argument_list|()
block|;
name|void
name|addHandler
argument_list|(
name|QKmsUdevHandler
operator|*
argument_list|)
block|;
name|private
operator|:
name|QList
operator|<
name|QPointer
operator|<
name|QKmsUdevHandler
operator|>
expr|>
name|m_handlers
block|;
name|QMap
operator|<
name|QString
block|,
name|QPointer
operator|<
name|QObject
operator|>
expr|>
name|m_devices
block|;     struct
name|udev
operator|*
name|m_udev
block|;
name|void
name|scan
argument_list|()
block|;
name|bool
name|create
argument_list|(
expr|struct
name|udev_device
operator|*
argument_list|)
block|; }
decl_stmt|;
end_decl_stmt
begin_macro
name|QT_END_NAMESPACE
end_macro
begin_endif
endif|#
directive|endif
end_endif
begin_comment
comment|// QKMSUDEVLISTENER_H
end_comment
end_unit
