begin_unit
begin_comment
comment|/**************************************************************************** ** ** Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies). ** All rights reserved. ** Contact: Nokia Corporation (qt-info@nokia.com) ** ** This file is part of the QtOpenVG module of the Qt Toolkit. ** ** $QT_BEGIN_LICENSE:LGPL$ ** No Commercial Usage ** This file contains pre-release code and may not be distributed. ** You may use this file in accordance with the terms and conditions ** contained in the Technology Preview License Agreement accompanying ** this package. ** ** GNU Lesser General Public License Usage ** Alternatively, this file may be used under the terms of the GNU Lesser ** General Public License version 2.1 as published by the Free Software ** Foundation and appearing in the file LICENSE.LGPL included in the ** packaging of this file.  Please review the following information to ** ensure the GNU Lesser General Public License version 2.1 requirements ** will be met: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html. ** ** In addition, as a special exception, Nokia gives you certain additional ** rights.  These rights are described in the Nokia Qt LGPL Exception ** version 1.1, included in the file LGPL_EXCEPTION.txt in this package. ** ** If you have questions regarding the use of this file, please contact ** Nokia at qt-info@nokia.com. ** ** ** ** ** ** ** ** ** $QT_END_LICENSE$ ** ****************************************************************************/
end_comment
begin_ifndef
ifndef|#
directive|ifndef
name|QPAINTENGINE_VG_P_H
end_ifndef
begin_define
DECL|macro|QPAINTENGINE_VG_P_H
define|#
directive|define
name|QPAINTENGINE_VG_P_H
end_define
begin_comment
comment|//
end_comment
begin_comment
comment|//  W A R N I N G
end_comment
begin_comment
comment|//  -------------
end_comment
begin_comment
comment|//
end_comment
begin_comment
comment|// This file is not part of the Qt API.  It exists purely as an
end_comment
begin_comment
comment|// implementation detail.  This header file may change from version to
end_comment
begin_comment
comment|// version without notice, or even be removed.
end_comment
begin_comment
comment|//
end_comment
begin_comment
comment|// We mean it.
end_comment
begin_comment
comment|//
end_comment
begin_include
include|#
directive|include
file|<QtGui/private/qpaintengineex_p.h>
end_include
begin_include
include|#
directive|include
file|<QtGui/private/qtextureglyphcache_p.h>
end_include
begin_macro
name|QT_BEGIN_NAMESPACE
end_macro
begin_struct_decl
struct_decl|struct
name|QFixedPoint
struct_decl|;
end_struct_decl
begin_decl_stmt
DECL|variable|QVGPaintEnginePrivate
name|class
name|QVGPaintEnginePrivate
decl_stmt|;
end_decl_stmt
begin_decl_stmt
DECL|variable|QPixmapData
name|class
name|QPixmapData
decl_stmt|;
end_decl_stmt
begin_decl_stmt
DECL|variable|QVGEGLWindowSurfacePrivate
name|class
name|QVGEGLWindowSurfacePrivate
decl_stmt|;
end_decl_stmt
begin_decl_stmt
name|class
name|Q_OPENVG_EXPORT
name|QVGPainterState
range|:
name|public
name|QPainterState
block|{
name|public
operator|:
name|QVGPainterState
argument_list|(
name|QVGPainterState
operator|&
name|other
argument_list|)
block|;
name|QVGPainterState
argument_list|()
block|;
operator|~
name|QVGPainterState
argument_list|()
block|;
name|bool
name|isNew
block|;
name|QRegion
name|clipRegion
block|;
name|QPaintEngine
operator|::
name|DirtyFlags
name|savedDirty
block|; }
decl_stmt|;
end_decl_stmt
begin_decl_stmt
name|class
name|Q_OPENVG_EXPORT
name|QVGPaintEngine
range|:
name|public
name|QPaintEngineEx
block|{
name|Q_DECLARE_PRIVATE
argument_list|(
argument|QVGPaintEngine
argument_list|)
name|public
operator|:
name|QVGPaintEngine
argument_list|()
block|;
operator|~
name|QVGPaintEngine
argument_list|()
block|;
name|Type
name|type
argument_list|()
specifier|const
block|{
return|return
name|OpenVG
return|;
block|}
name|QPainterState
operator|*
name|createState
argument_list|(
argument|QPainterState *orig
argument_list|)
specifier|const
block|;
name|bool
name|begin
argument_list|(
name|QPaintDevice
operator|*
name|pdev
argument_list|)
block|;
name|bool
name|end
argument_list|()
block|;
name|void
name|draw
argument_list|(
specifier|const
name|QVectorPath
operator|&
name|path
argument_list|)
block|;
name|void
name|fill
argument_list|(
specifier|const
name|QVectorPath
operator|&
name|path
argument_list|,
specifier|const
name|QBrush
operator|&
name|brush
argument_list|)
block|;
name|void
name|stroke
argument_list|(
specifier|const
name|QVectorPath
operator|&
name|path
argument_list|,
specifier|const
name|QPen
operator|&
name|pen
argument_list|)
block|;
name|void
name|clip
argument_list|(
argument|const QVectorPath&path
argument_list|,
argument|Qt::ClipOperation op
argument_list|)
block|;
name|void
name|clip
argument_list|(
argument|const QRect&rect
argument_list|,
argument|Qt::ClipOperation op
argument_list|)
block|;
name|void
name|clip
argument_list|(
argument|const QRegion&region
argument_list|,
argument|Qt::ClipOperation op
argument_list|)
block|;
name|void
name|clip
argument_list|(
argument|const QPainterPath&path
argument_list|,
argument|Qt::ClipOperation op
argument_list|)
block|;
name|void
name|clipEnabledChanged
argument_list|()
block|;
name|void
name|penChanged
argument_list|()
block|;
name|void
name|brushChanged
argument_list|()
block|;
name|void
name|brushOriginChanged
argument_list|()
block|;
name|void
name|opacityChanged
argument_list|()
block|;
name|void
name|compositionModeChanged
argument_list|()
block|;
name|void
name|renderHintsChanged
argument_list|()
block|;
name|void
name|transformChanged
argument_list|()
block|;
name|void
name|fillRect
argument_list|(
specifier|const
name|QRectF
operator|&
name|rect
argument_list|,
specifier|const
name|QBrush
operator|&
name|brush
argument_list|)
block|;
name|void
name|fillRect
argument_list|(
specifier|const
name|QRectF
operator|&
name|rect
argument_list|,
specifier|const
name|QColor
operator|&
name|color
argument_list|)
block|;
name|void
name|drawRoundedRect
argument_list|(
argument|const QRectF&rect
argument_list|,
argument|qreal xrad
argument_list|,
argument|qreal yrad
argument_list|,
argument|Qt::SizeMode mode
argument_list|)
block|;
name|void
name|drawRects
argument_list|(
argument|const QRect *rects
argument_list|,
argument|int rectCount
argument_list|)
block|;
name|void
name|drawRects
argument_list|(
argument|const QRectF *rects
argument_list|,
argument|int rectCount
argument_list|)
block|;
name|void
name|drawLines
argument_list|(
argument|const QLine *lines
argument_list|,
argument|int lineCount
argument_list|)
block|;
name|void
name|drawLines
argument_list|(
argument|const QLineF *lines
argument_list|,
argument|int lineCount
argument_list|)
block|;
name|void
name|drawEllipse
argument_list|(
specifier|const
name|QRectF
operator|&
name|r
argument_list|)
block|;
name|void
name|drawEllipse
argument_list|(
specifier|const
name|QRect
operator|&
name|r
argument_list|)
block|;
name|void
name|drawPath
argument_list|(
specifier|const
name|QPainterPath
operator|&
name|path
argument_list|)
block|;
name|void
name|drawPoints
argument_list|(
argument|const QPointF *points
argument_list|,
argument|int pointCount
argument_list|)
block|;
name|void
name|drawPoints
argument_list|(
argument|const QPoint *points
argument_list|,
argument|int pointCount
argument_list|)
block|;
name|void
name|drawPolygon
argument_list|(
argument|const QPointF *points
argument_list|,
argument|int pointCount
argument_list|,
argument|PolygonDrawMode mode
argument_list|)
block|;
name|void
name|drawPolygon
argument_list|(
argument|const QPoint *points
argument_list|,
argument|int pointCount
argument_list|,
argument|PolygonDrawMode mode
argument_list|)
block|;
name|void
name|drawPixmap
argument_list|(
specifier|const
name|QRectF
operator|&
name|r
argument_list|,
specifier|const
name|QPixmap
operator|&
name|pm
argument_list|,
specifier|const
name|QRectF
operator|&
name|sr
argument_list|)
block|;
name|void
name|drawPixmap
argument_list|(
specifier|const
name|QPointF
operator|&
name|pos
argument_list|,
specifier|const
name|QPixmap
operator|&
name|pm
argument_list|)
block|;
name|void
name|drawImage
argument_list|(
argument|const QRectF&r
argument_list|,
argument|const QImage&pm
argument_list|,
argument|const QRectF&sr
argument_list|,
argument|Qt::ImageConversionFlags flags = Qt::AutoColor
argument_list|)
block|;
name|void
name|drawImage
argument_list|(
specifier|const
name|QPointF
operator|&
name|pos
argument_list|,
specifier|const
name|QImage
operator|&
name|image
argument_list|)
block|;
name|void
name|drawTiledPixmap
argument_list|(
specifier|const
name|QRectF
operator|&
name|r
argument_list|,
specifier|const
name|QPixmap
operator|&
name|pixmap
argument_list|,
specifier|const
name|QPointF
operator|&
name|s
argument_list|)
block|;
name|void
name|drawPixmapFragments
argument_list|(
argument|const QPainter::PixmapFragment *drawingData
argument_list|,
argument|int dataCount
argument_list|,
argument|const QPixmap&pixmap
argument_list|,
argument|QFlags<QPainter::PixmapFragmentHint> hints
argument_list|)
block|;
name|void
name|drawTextItem
argument_list|(
specifier|const
name|QPointF
operator|&
name|p
argument_list|,
specifier|const
name|QTextItem
operator|&
name|textItem
argument_list|)
block|;
name|void
name|drawStaticTextItem
argument_list|(
name|QStaticTextItem
operator|*
name|staticTextItem
argument_list|)
block|;
name|bool
name|drawCachedGlyphs
argument_list|(
argument|int numGlyphs
argument_list|,
argument|const glyph_t *glyphs
argument_list|,
argument|const QFont&font
argument_list|,
argument|QFontEngine *fontEngine
argument_list|,
argument|const QPointF&p
argument_list|,
argument|const QFixedPoint *positions
argument_list|)
block|;
name|void
name|setState
argument_list|(
name|QPainterState
operator|*
name|s
argument_list|)
block|;
name|QVGPainterState
operator|*
name|state
argument_list|()
block|{
return|return
name|static_cast
operator|<
name|QVGPainterState
operator|*
operator|>
operator|(
name|QPaintEngineEx
operator|::
name|state
argument_list|()
operator|)
return|;
block|}
specifier|const
name|QVGPainterState
operator|*
name|state
argument_list|()
specifier|const
block|{
return|return
name|static_cast
operator|<
specifier|const
name|QVGPainterState
operator|*
operator|>
operator|(
name|QPaintEngineEx
operator|::
name|state
argument_list|()
operator|)
return|;
block|}
name|void
name|beginNativePainting
argument_list|()
block|;
name|void
name|endNativePainting
argument_list|()
block|;
name|QPixmapFilter
operator|*
name|pixmapFilter
argument_list|(
argument|int type
argument_list|,
argument|const QPixmapFilter *prototype
argument_list|)
block|;
name|QVGPaintEnginePrivate
operator|*
name|vgPrivate
argument_list|()
block|{
name|Q_D
argument_list|(
name|QVGPaintEngine
argument_list|)
block|;
return|return
name|d
return|;
block|}
name|void
name|fillRegion
argument_list|(
specifier|const
name|QRegion
operator|&
name|region
argument_list|,
specifier|const
name|QColor
operator|&
name|color
argument_list|,
specifier|const
name|QSize
operator|&
name|surfaceSize
argument_list|)
block|;
name|protected
operator|:
name|QVGPaintEngine
argument_list|(
name|QVGPaintEnginePrivate
operator|&
name|data
argument_list|)
block|;
name|private
operator|:
name|void
name|restoreState
argument_list|(
argument|QPaintEngine::DirtyFlags dirty
argument_list|)
block|;
name|void
name|updateScissor
argument_list|()
block|;
name|QRegion
name|defaultClipRegion
argument_list|()
block|;
name|bool
name|isDefaultClipRegion
argument_list|(
specifier|const
name|QRegion
operator|&
name|region
argument_list|)
block|;
name|bool
name|isDefaultClipRect
argument_list|(
specifier|const
name|QRect
operator|&
name|rect
argument_list|)
block|;
name|bool
name|clearRect
argument_list|(
specifier|const
name|QRectF
operator|&
name|rect
argument_list|,
specifier|const
name|QColor
operator|&
name|color
argument_list|)
block|;
name|bool
name|canVgWritePixels
argument_list|(
argument|const QImage&image
argument_list|)
specifier|const
block|; }
decl_stmt|;
end_decl_stmt
begin_macro
name|QT_END_NAMESPACE
end_macro
begin_endif
endif|#
directive|endif
end_endif
end_unit
